name: Pink Wilder
favicon: null
layout_spectrum: 0.9509388930164278
typography_spectrum: 0.4227963543962687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.17482296144589782
  lightness: 0.11995450686663389
  saturation: 0.7347169567365199
  rhythmicContrast: 0.8667923512402922
purpose: []
