name: Pink Wilder
favicon: null
layout_spectrum: 0.75424
typography_spectrum: 0.50585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0.11995450686663389
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
